name: worldcup-results
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - xgboost
  - lightgbm
  - catboost
